// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://detwkdkedbwsjbwvjoiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHdrZGtlZGJ3c2pid3Zqb2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTI3MzUsImV4cCI6MjA2ODM2ODczNX0.i1lin-f33Fjmd8qljv2jlAD01sgjveNDQXWRplzjbcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});